# reproducibility
deterministic: False
random_seed: 42

# training

pl_trainer:
  fast_dev_run: False # Enable this for debug purposes
  gpus: 1
  precision: 32
  #max_steps: 10000
  max_epochs: 50
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 0.5

monitor_metric: 'val/loss'
monitor_metric_mode: 'min'

early_stopping:
  patience: 5
  verbose: False

model_checkpoints:
  save_top_k: 2
  verbose: True

stochastic_weight_averaging:
  active: False
  swa_epoch_start: 3

