# log frequency
val_check_interval: 1.0
progress_bar_refresh_rate: 5

wandb:
  project: dlai-stonks-new
  entity: null
  log_model: 'all'
  mode: 'online'
  save_code: True

wandb_watch:
  log: 'all'
  log_freq: 100

lr_monitor:
  logging_interval: "epoch"
  log_momentum: False
