data_path: ${oc.env:PROJECT_ROOT}/data/yahoofinance_crypto/*.csv
input_columns:
  - Log(PctChange(Open_1h))
  - Log(PctChange(Sma9(Open_1h)))
  - Log(Open_1h - Sma9(Open_1h))
  - Log(PctChange(Sma12(Open_1h)))
  - Log(Open_1h - Sma12(Open_1h))
  - Log(PctChange(Sma26(Open_1h)))
  - Log(Open_1h - Sma26(Open_1h))
  - Log(PctChange(Sma9(Shift1(Open_1h))))
  - Log(Shift1(Open_1h) - Sma9(Shift1(Open_1h)))
  - Log(PctChange(Sma12(Shift1(Open_1h))))
  - Log(Shift1(Open_1h) - Sma12(Shift1(Open_1h)))
  - Log(PctChange(Sma26(Shift1(Open_1h))))
  - Log(Shift1(Open_1h) - Sma26(Shift1(Open_1h)))
  - Log(Open - Sma9(Open_1h))
  - Log(Open - Sma12(Open_1h))
  - Log(Open - Sma26(Open_1h))
  - Log(PctChange(Open))
  - Log(PctChange(Sma9(Open)))
  - Log(Open - Sma9(Open))
  - Log(PctChange(Sma12(Open)))
  - Log(Open - Sma12(Open))
  - Log(PctChange(Sma26(Open)))
  - Log(Open - Sma26(Open))
continuous_targets:
  - Target
categorical_targets:
  - TargetCategorical
n_classes: 3
train_period:
  start: 2021-08-01
  end: 2021-10-01
val_period:
  start: ${dataset_conf.train_period.end}
  end: 2021-12-01
