defaults:
  - data_path: yahoofinance5min.yaml

window_length: 1
dataset_reader:
  _target_: src.dataset_readers.feature_set_2_trendprediction_reader
  resample: 5min
  trend_period: 10
  target_col: TargetCategorical
  alpha: 0.008

input_columns:
  - NormOHLC4(Open)
  - NormOHLC4(High)
  - NormOHLC4(Low)
  - NormOHLC4(Close)
  - NormOHLC4(Sma9(Open))
  - NormOHLC4(Std9(Open))
  - NormOHLC4(Sma26(Open))
  - NormOHLC4(Std26(Open))
continuous_targets: null
categorical_targets:
  - TargetCategorical
n_classes: 3
train_period:
  start: 2017-01-01
  end: 2021-10-01
val_period:
  start: ${dataset_conf.train_period.end}
  end: 2021-12-01
window_skip: 1
minmax_scale_windows: False
zscore_scale_windows: False
future_window_length: 0
return_dicts: False
clamp_values: null
channels_last: True
