defaults:
  - data_path: yahoofinance5min.yaml

window_length: 1
dataset_reader:
  _target_: src.dataset_readers.qbin_reader
  q: 3

input_columns:
  - Log(PctChange(Open_1h))
  - Log(PctChange(Sma9(Open_1h)))
  - Log(Open_1h - Sma9(Open_1h))
  - Log(PctChange(Sma12(Open_1h)))
  - Log(Open_1h - Sma12(Open_1h))
  - Log(PctChange(Sma26(Open_1h)))
  - Log(Open_1h - Sma26(Open_1h))
  - Log(Open - Sma9(Open_1h))
  - Log(Open - Sma12(Open_1h))
  - Log(Open - Sma26(Open_1h))
  - Log(PctChange(Open))
  - Log(PctChange(Sma9(Open)))
  - Log(Open - Sma9(Open))
  - Log(PctChange(Sma12(Open)))
  - Log(Open - Sma12(Open))
  - Log(PctChange(Sma26(Open)))
  - Log(Open - Sma26(Open))
  - LogCumReturn12(Open)
  - LogCumReturn48(Open)
  - LogCumReturn488(Open)
continuous_targets:
  - Target
categorical_targets:
  - TargetCategorical
n_classes: ${dataset_conf.dataset_reader.q}
train_period:
  start: 2021-05-01
  end: 2021-10-01
val_period:
  start: ${dataset_conf.train_period.end}
  end: 2021-12-01
window_skip: 1
minmax_scale_windows: False
zscore_scale_windows: False
future_window_length: 0
return_dicts: False
clamp_values: null
channels_last: True
