defaults:
  - data_path: btc_ccxt.yaml

dataset_reader:
  _target_: src.dataset_readers.goodfeatures_reader
  resample: 5min
  trend_period: 10
  std_mult: 2.0

input_columns:
  - Zscore10(Close)
  - Zscore30(Close)
  - Zscore50(Close)
  - Zscore100(Close)
  - Zscore200(Close)
  - Zscore10(Volume)
  - Zscore30(Volume)
  - Zscore50(Log(PctChange(Close)))
  - Zscore200(Log(PctChange(Close)))
continuous_targets: null
categorical_targets:
  - TargetAdaCategorical
n_classes: 3
train_period:
  start: 2017-01-01
  end: 2021-10-01
val_period:
  start: ${dataset_conf.train_period.end}
  end: 2021-12-01
window_skip: 128
window_length: 128
minmax_scale_windows: False
zscore_scale_windows: False
future_window_length: 0
return_dicts: True
clamp_values: null
channels_last: False
