defaults:
  - data_path: yahoofinance5min.yaml

window_length: 1
dataset_reader:
  _target_: src.dataset_readers.feature_set_2_reader

input_columns:
  - NormOHLC4(Open)
  - NormOHLC4(High)
  - NormOHLC4(Low)
  - NormOHLC4(Close)
  - NormOHLC4(Sma9(Open))
  - NormOHLC4(Std9(Open))
  - NormOHLC4(Sma26(Open))
  - NormOHLC4(Std26(Open))
continuous_targets:
  - FutureMean
  - FutureStd
categorical_targets:
  #  - TargetCategorical
n_classes: 3
train_period:
  start: 2021-05-01
  end: 2021-10-01
val_period:
  start: ${dataset_conf.train_period.end}
  end: 2021-12-01
window_skip: 1
