data_path: ${oc.env:PROJECT_ROOT}/data/yahoofinance_crypto/*.csv
dataset_reader:
  _target_: src.dataset_readers.zscore_reader
  normalize_colnames: 
    - Open
    - Log(Open - Sma9(Open))
    - Log(Open - Sma12(Open))
    - Log(Open - Sma26(Open))
    - LogCumReturn12(Open)
    - LogCumReturn48(Open)
    - LogCumReturn288(Open)
input_columns:
  - Zscore20(Open)
  - Zscore20(Log(Open - Sma9(Open)))
  - Zscore20(Log(Open - Sma12(Open)))
  - Zscore20(Log(Open - Sma26(Open)))
  - Zscore20(LogCumReturn12(Open))
  - Zscore20(LogCumReturn48(Open))
  - Zscore20(LogCumReturn288(Open))
  - Zscore50(Open)
  - Zscore50(Log(Open - Sma9(Open)))
  - Zscore50(Log(Open - Sma12(Open)))
  - Zscore50(Log(Open - Sma26(Open)))
  - Zscore50(LogCumReturn12(Open))
  - Zscore50(LogCumReturn48(Open))
  - Zscore50(LogCumReturn288(Open))
  - Zscore100(Open)
  - Zscore100(Log(Open - Sma9(Open)))
  - Zscore100(Log(Open - Sma12(Open)))
  - Zscore100(Log(Open - Sma26(Open)))
  - Zscore100(LogCumReturn12(Open))
  - Zscore100(LogCumReturn48(Open))
  - Zscore100(LogCumReturn288(Open))

continuous_targets:
  - Target
categorical_targets:
  - TargetCategorical
n_classes: 3
train_period:
  start: 2021-05-01
  end: 2021-10-01
val_period:
  start: ${dataset_conf.train_period.end}
  end: 2021-12-01
