defaults:
  - data_path: yahoofinance5min.yaml

name: zscore_by_open_ohlcvtarget
dataset_reader:
  _target_: src.dataset_readers.zscore_by_ohlc4_reader
  resample: 5min
  zscore_period: 100
  std_mult: 2

input_columns:
  - Zscore${dataset_conf.dataset_reader.zscore_period}(Open)
  - Zscore${dataset_conf.dataset_reader.zscore_period}(High)
  - Zscore${dataset_conf.dataset_reader.zscore_period}(Low)
  - Zscore${dataset_conf.dataset_reader.zscore_period}(Close)
    #- Log(PctChange(Open))
continuous_targets:
  - FutureOpen
  - FutureHigh
  - FutureLow
  - FutureClose
    #- FutureLogReturn
categorical_targets: null
n_classes: 3
train_period:
  start: 2018-05-01
  end: 2021-10-01
val_period:
  start: ${dataset_conf.train_period.end}
  end: 2021-12-01
window_skip: 1
window_length: 7
minmax_scale_windows: False
zscore_scale_windows: False
future_window_length: 0
return_dicts: True
clamp_values: null
channels_last: True
