# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - mytag

defaults:
  - dataset_conf: trend_fixclf_multivar
  - data: default
  - hydra: default
  - logging: default
  - model: lstm
  - lr_scheduler: default
  - optim: adam
  - train: default
  #### KEEP THIS AS THE LAST
  - experiment: lstm_large
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
