# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - mytag

defaults:
  - data: default
  - dataset_conf: default
  - hydra: default
  - logging: default
  - losses: default
  - model: default
  - lr_scheduler: default
  - optim: adam
  - train: default
  #### KEEP THIS AS THE LAST
  - experiment: default
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
