_target_: src.lit_models.TimeSeriesModule
name: autoencoder_mlp
model:
  _target_: src.models.ClassifierWithAutoEncoder
  n_classes: ${dataset_conf.n_classes}
  autoencoder:
    _target_: src.models.FeedForwardAutoEncoder
    in_size: ${length:${dataset_conf.input_columns}}
    window_length: ${dataset_conf.window_length}
    hidden_sizes: [20,10,5]
    activation:
      _target_: ${model.activation}
    dropout: ${model.dropout}

classification_loss_fn:
  _target_: torch.nn.CrossEntropyLoss
regression_loss_fn:
reconstruction_loss_fn:
  _target_: torch.nn.MSELoss
reconstruction_loss_weight:
  1
dropout:
  0.0
activation:
  torch.nn.Tanh
