_target_: src.lit_models.MLPClassifierModel
model:
  _target_: src.models.Classifier
  n_classes: ${dataset_conf.n_classes}
  feature_extractor:
    _target_: src.models.SimpleFeedForward
    in_size: ${length:${dataset_conf.input_columns}}
    hidden_sizes: [200,100,50]
    activation:
      _target_: torch.nn.Tanh
    dropout:
      0.1
classification_loss_fn:
  _target_: torch.nn.CrossEntropyLoss
reconstruction_loss_fn:
  _target_: torch.nn.MSELoss
reconstruction_loss_weight:
  1
