defaults:
  - classification_loss_fn: crossentropy_dynweights.yaml

_target_: src.lightning_modules.TimeSeriesClassifier
name: tcn_seqtagger
model:
  _target_: src.models.Classifier
  feature_extractor:  
    _target_: src.models.TcnLstmEncoder
    tcn:
      _target_: src.models.TcnEncoder
      num_inputs: ${length:${dataset_conf.input_columns}}
      num_channels: [16,32,64,64]
      dropout: ${model.dropout}
      kernel_size: 2
      compression: 1
      channels_last: ${dataset_conf.channels_last}
      residual: True
      activation: ${model.activation}
      dilated_conv: True
    lstm:
      _target_: src.models.LstmModel
      in_size: ${last:${..tcn.num_channels}}
      hidden_size: 64
      num_layers: 1
      dropout: ${model.dropout}
  num_classes: ${dataset_conf.n_classes}
  feature_dim: ${.feature_extractor.lstm.hidden_size}
regression_loss_fn: null
reconstruction_loss_fn: null
variational_beta: 1
reconstruction_loss_weight:
  1
dropout: 0.1
activation:
  _target_: torch.nn.LeakyReLU
flatten_input: False
