_target_: src.lit_models.TimeSeriesVAE
name: tcn_vae
model:
  _target_: src.models.TcnVAE
  num_inputs: ${length:${dataset_conf.input_columns}}
  latent_size: 32
  kernel_size: 2
  num_channels: [16]
  sequence_length: ${dataset_conf.window_length}
  dropout: ${model.dropout}
  stride: 1
  channels_last: ${dataset_conf.channels_last}
classification_loss_fn: null
regression_loss_fn: null
reconstruction_loss_fn:
  _target_: torch.nn.MSELoss
  reduction: mean
diff_loss: False
norm_difference_loss: False
variational_beta: 1
reconstruction_loss_weight:
  1
dropout: 0.1
activation:
  torch.nn.ReLU
flatten_input: False
