_target_: src.lit_models.TimeSeriesModule
name: transformer
model:
  _target_: src.models.Regressor
  n_outputs: ${length:${dataset_conf.continuous_targets}}
  use_feature_scaler: False
  feature_extractor:
    _target_: src.models.TransformerForecaster
    in_size: ${length:${dataset_conf.input_columns}}
    transformer:
      _target_: src.models.CausalTransformer
      feature_size: 64
      n_heads: 4
      num_layers: 1
      dropout: ${model.dropout}
      positional_encoding: sine
    embed_by_repetition: False
classification_loss_fn:
regression_loss_fn:
  _target_: torch.nn.MSELoss
reconstruction_loss_fn:
reconstruction_loss_weight:
  1
dropout: 0.1
activation:
  torch.nn.ReLU
flatten_input: False
