defaults:
  - classification_loss_fn: crossentropy_dynweights.yaml

_target_: src.lightning_modules.TimeSeriesClassifier
name: transformer
model:
  _target_: src.models.Classifier
  num_classes: ${dataset_conf.n_classes}
  feature_extractor:
    _target_: src.models.TransformerForecaster
    in_size: ${length:${dataset_conf.input_columns}}
    embedding:
      _target_:
        src.models.TCNWrapper
      num_inputs: ${length:${dataset_conf.input_columns}}
      num_channels:
        - 32
        - 64
        - ${model.model.feature_extractor.transformer.feature_size}
      kernel_size: 2
      dropout: ${model.dropout}
    transformer:
      _target_: src.models.CausalTransformer
      feature_size: 128
      feedforward_size: 512
      n_heads: 2
      num_layers: 1
      dropout: ${model.dropout}
      positional_encoding: sine
    embed_by_repetition: False
#   decoder:
#     _target_: torch.nn.Linear
#     in_features: ${model.model.encoder.transformer.feature_size}
#     out_features: ${length:${dataset_conf.input_columns}}
regression_loss_fn: null
reconstruction_loss_fn: null
reconstruction_loss_weight:
  1
dropout: 0.1
activation:
  torch.nn.LeakyReLU
flatten_input: False
