_target_: src.lightning_modules.TimeSeriesModule
name: transformer_vq
model:
  _target_: src.models.Regressor
  n_outputs: ${length:${dataset_conf.continuous_targets}}
  use_feature_scaler: False
  feature_extractor:
    _target_: src.models.TransformerForecaster
    in_size: ${length:${dataset_conf.input_columns}}
    transformer:
      _target_: src.models.CausalTransformer
      feature_size: 256
      n_heads: 4
      num_layers: 1
      dropout: ${model.dropout}
    embed_by_repetition: False
quantizer:
  _target_: vector_quantize_pytorch.VectorQuantize
  dim: ${model.model.feature_extractor.in_size}
  codebook_size: 1024
  eps: 1e-8
  kmeans_init: True
  use_cosine_sim: True

classification_loss_fn:
regression_loss_fn:
  _target_: torch.nn.MSELoss
reconstruction_loss_fn:
  _target_: torch.nn.MSELoss
reconstruction_loss_weight:
  1
dropout: 0.1
activation:
  torch.nn.ReLU
flatten_input: False
