_target_: src.lit_models.TimeSeriesVAE
name: transformer
model:
  _target_: src.models.VariationalAutoEncoder
  encoder:
    _target_: src.models.NonLinear
    in_size: ${length:${dataset_conf.input_columns}}
    hidden_size: ${model.latent_size}
    activation:
      _target_: torch.nn.Sigmoid
  decoder:
    _target_: src.models.NonLinear
    in_size: ${model.latent_size}
    hidden_size: ${length:${dataset_conf.input_columns}}
    activation:
      _target_: torch.nn.Sigmoid
  latent_size: ${model.latent_size}

classification_loss_fn: null
regression_loss_fn: null
reconstruction_loss_fn:
  _target_: src.models.VaeLoss
  variational_beta: 1
dropout: 0.1
activation:
  _target_:
    torch.nn.ReLU
flatten_input: False
latent_size: 2

