optimizer:
  #  Adam-oriented deep learning
  _target_: torch.optim.AdamW
  #  These are all default parameters for the Adam optimizer
  lr: 0.001
  betas: [ 0.9, 0.999 ]
  eps: 1e-15
  weight_decay: 0

use_lr_scheduler: ${lr_scheduler.use_lr_scheduler}
lr_scheduler: ${lr_scheduler.scheduler}
