name: cosine_annealing_warm_restarts
use_lr_scheduler: True
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2
  eta_min: 1e-6 # min value for the lr
  last_epoch: -1
  verbose: True
